### ISSUE TITLE
backdrop pseudo element

### ISSUE THREAD

**Issue by thejackshelton** [oddbird/popover-polyfill#130]
Is it possible to add a backdrop polyfilled pseudo element maybe? I noticed there is a backdrop in the native html spec, and it works great in supported browsers, but looks like it doesn't in unsupported browsers like firefox.

**Comment by thagxt** [comment]
Yes, that would be nice to have. However, I ended up doing the following:

```css
.\:popover-open::after {
    content: '';
    position: fixed;
    inset: 0px;
    z-index: -1;
    pointer-events: none;
    background-color: red;
}
```
