### ISSUE TITLE
Problems with overwriting popover styling for Firefox

### ISSUE THREAD

**Issue by anna-lach** [oddbird/popover-polyfill#147]
I’m currently working on a popover component and I’d like to overwrite some styling for the `[popover]` like `overflow` to visible etc., but in the Firefox it doesn’t work. Since there are styles added in the `popover.ts` file in the polyfill it looks like I cannot overwrite those styles in my app. It seems those styles from polyfill's `popover.ts` file have the highest specificity.

**Comment by merchanf-gg** [comment]
As far as I know popover is not yet available in firefox. https://caniuse.com/?search=popover

**Comment by anna-lach** [comment]
Thank you @keithamus. I tried with `[popover][popover]` but it's still not working properly. So for now maybe I'll mark some properties as `!important`, because I only need it for a few like `border`.

**Comment by jgerigmeyer** [comment]
@anna-lach This is released in [v0.3.4](https://github.com/oddbird/popover-polyfill/releases/tag/v0.3.4).

**Comment by jpzwarte** [comment]
I'm working with Anna on this. I *think* this has something to do with the shadow DOM: no matter what selectors I add to the scoped styling within the custom element, I cannot get it to "overwrite" the `border-*` styling of the polyfill. 

@jgerigmeyer the `:where([popover])` fix also doesn't help.

So afaics the only way to work around this is to use `!important` atm.

To clarify, we are doing something like this:

```css
// Doesn't matter if how many selectors you add here, the polyfill styles will always have a higher specificity
:host([popover]) {
  border: var(--_border);
}
```
