### ISSUE TITLE
Recommended example for :backdrop

### ISSUE THREAD

**Issue by jh3y** [oddbird/popover-polyfill#75]
Hey 👋

Might be cool to have some kind of support for `:backdrop` behavior or a heads-up on how you might implement that yourself.

Could be in something like:

```css
[popover].:open:before { ...backdropStyles }
@supports ([popover]:backdrop) { ...backdropStyles }
```

Although using the pseudoelement runs into the issue of getting the `:backdrop` beneath the content. Might be nice to give some kind of guided snippet for those wanting that behavior 👍 

@jh3y

**Comment by joshnuss** [comment]
One solution, if your browser supports `:has`:

```css
::backdrop, body:has(.\:popover-open)::before { 
  z-index: 1;
  content: '';
  width: 100%;
  height: 100%;
  position: fixed;
  left: 0;
  top: 0;

  background: #0004;
  backdrop-filter: blur(2px); 
}

.\:popover-open {
  z-index: 2;
}

[popup]:popover-open {
  z-index: 2;
}
```
